In [1]:
# random forest

In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
import pandas as pd


In [2]:
train=pd.read_csv('/Users/xiaoshuaiheng/Desktop/EE 627 Big Data/HW！/HW9/3/test2_5score.csv',header=None)
test=pd.read_csv('/Users/xiaoshuaiheng/Desktop/EE 627 Big Data/HW！/HW9/3/test_5score.csv',header=None)

In [3]:
trainX=train.iloc[:,2:7]
trainY=train.iloc[:,7]
test=test.iloc[:,2:7]

In [4]:
rf = RandomForestClassifier(max_depth=2,random_state=0)

In [5]:
rf.fit(trainX,trainY)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [7]:
#testY=rf.predict(test)

In [8]:
#testY

array([0, 0, 0, ..., 1, 0, 1])

In [7]:
testY=rf.predict_proba(test)

In [9]:
testY

array([[0.78877341, 0.21122659],
       [0.66824804, 0.33175196],
       [0.78877341, 0.21122659],
       ...,
       [0.07026286, 0.92973714],
       [0.78877341, 0.21122659],
       [0.07026286, 0.92973714]])

In [10]:
testY=testY[:,1]

In [11]:
testY

array([0.21122659, 0.33175196, 0.21122659, ..., 0.92973714, 0.21122659,
       0.92973714])

In [12]:
result=open('/Users/xiaoshuaiheng/Desktop/EE 627 Big Data/HW！/HW9/3/testY2.txt','w')
for i in range(len(testY)):
    result.write(str(testY[i])+'\n')

In [1]:
# reload
import pandas as pd
s=pd.read_csv('/Users/xiaoshuaiheng/Desktop/EE 627 Big Data/HW！/HW9/3/prob_rf.csv')
s.head(5)

UseID  TrackID     Score
0  199810   208019  0.211227
1  199810    74139  0.331752
2  199810     9903  0.211227
3  199810   242681  0.211227
4  199810    18515  0.639685

In [3]:
s1=s.sort_values(by=['UseID','Score'])
s1.head(5)

UseID  TrackID     Score
0  199810   208019  0.211227
2  199810     9903  0.211227
3  199810   242681  0.211227
1  199810    74139  0.331752
4  199810    18515  0.639685

In [4]:
j=0
for i in range(120000):
    if j<3:
        s1.iloc[i,2]=0
    else:
        s1.iloc[i,2]=1
    j+=1
    if j==6:
        j=0

In [5]:
s1

UseID  TrackID  Score
0       199810   208019    0.0
2       199810     9903    0.0
3       199810   242681    0.0
1       199810    74139    1.0
4       199810    18515    1.0
...        ...      ...    ...
119996  249010    86104    0.0
119998  249010   293818    0.0
119994  249010   110470    1.0
119997  249010   186634    1.0
119999  249010   262811    1.0

[120000 rows x 3 columns]

In [6]:
import numpy as np
for i in range(120000):
    if i%6==0:
        matrix=np.zeros((6,3))
        for j in range(6):
            matrix[j,0]=s1.iloc[i+j,0]
            matrix[j,1]=s1.iloc[i+j,1]
            matrix[j,2]=s1.iloc[i+j,2]
    for k in range(6):
        if matrix[k,0]==s.iloc[i,0] and matrix[k,1]==s.iloc[i,1]:
            s.iloc[i,2]=matrix[k,2]
            break

In [7]:
s

UseID  TrackID  Score
0       199810   208019    0.0
1       199810    74139    1.0
2       199810     9903    0.0
3       199810   242681    0.0
4       199810    18515    1.0
...        ...      ...    ...
119995  249010    72192    0.0
119996  249010    86104    0.0
119997  249010   186634    1.0
119998  249010   293818    0.0
119999  249010   262811    1.0

[120000 rows x 3 columns]

In [8]:
s.to_csv('/Users/xiaoshuaiheng/Desktop/EE 627 Big Data/HW！/HW9/3/result_rf.csv')